### ISSUE TITLE
fix: typing issues

### ISSUE THREAD

**Issue by paul-thebaud** [paul-thebaud/func-client#3]
Issues might occur when using custom "shortcut" function, such as:

```typescript
function createResource<D extends ModelDefinition, I extends ModelInstance<D>>(i: I) {}

const i = new User()

// Type error
createResource(i)
```

**Comment by paul-thebaud** [comment]
@mthebaud, the package types have been reworked and simplified!

The package has been renamed to `foscia`, so you should remove the previous one and install this one (and replace import reference from).

The above example can now be rewritten as (with your previous "includeArg" param):

```typescript
function createResource<I extends ModelInstance>(i: I, includeArgs: ModelRelationDotKey<I>) {
    action().use(create(i)).use(include(i)).run(oneOrFail())
}

const i = new User()

// Type error
createResource(i, 'foo')
```

**Comment by mthebaud** [comment]
Thanks, I think there is still sometimes a problem with `fill` method : 

**Currently**, to have a correct typing, I have to do
```
async function setTodoItemDoneAt(
  todoItem: ModelInstance<ModelClass<TodoItem>>,
) {
  await updateResource(fill(todoItem, { doneAt: new Date() }));
}
```

I would **expect to be able to do**
```
async function setTodoItemDoneAt(todoItem: TodoItem) {
  await updateResource(fill(todoItem, { doneAt: new Date() }));
}
```

This is I guess linked to my `updateResource(...)` method

```
export const updateResource = async <
  D extends ModelClass,
  T extends ModelInstance<D>,
>(
  resource: T,
  includeArg?: ModelRelationDotKey<D>,
): Promise<T> => {...}
```

**Comment by paul-thebaud** [comment]
Looks like I have a bit of research to do with again 😭

What happens if you change your `updateResource` to follow my example above with only one generic type (the closing comment)? Does it work?

**Comment by mthebaud** [comment]
It's now working with 

```
export const updateResource = async <T extends ModelInstance>(
  resource: T,
  includeArg?: ModelRelationDotKey<T>,
): Promise<T> => {...}
```
called by 
```
async function setTodoItemDoneAt(todoItem: TodoItem) {
  await updateResource(fill(todoItem, { doneAt: new Date() }));
}
```

**Comment by paul-thebaud** [comment]
There are still issues with custom generic of actions (create, etc.) mixed with generic helpers (fill, etc.).

**Comment by paul-thebaud** [comment]
Looks finally OK. In your previous example, you was using `ModelRelationDotKey<T>` as your `includeArg` typing.
Please note that `ModelRelationDotKey<T>` represent ONE relation key. If you wish to be able to provide an array, you should use `ModelRelationDotKey<T>[]`.
